# Generated by Django 5.2.1 on 2025-05-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_deparment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='deparment',
            new_name='designation',
        ),
    ]
